GET http://localhost:8080/endpoints HTTP/1.1


###

POST http://localhost:8080/endpoints HTTP/1.1
content-type: application/json

{
    "name": "test 2",
    "url": "http://localhost:8081/health",
    "check_frequency": 2,
    "notify_to": "bruno.uemura@gmail.com"
}